### ISSUE TITLE
undefined method named "addAnnotatedClassesToCompile"

### ISSUE THREAD

**Issue by elfin-sbreuers** [symfony/symfony-docs#13603]
Hey there,

following the documentation on https://symfony.com/doc/4.4/bundles/extension.html, I wanted to use the method  `addAnnotatedClassesToCompile`. 

Then debugging the config with `./bin/console debug:config` delivers the following error:

```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\UndefinedMethodException: Attempted to call an undefined method named "addAnnotatedClassesToCompile" of class ...
```
Doing a grep search shows that the method is defined in `symfony/http-kernel/DependencyInjection/Extension.php` not in `symfony/dependency-injection/Extension/Extension.php`, that is used in the documentation.

Cheers,

Sebastian

**Comment by xabbuh** [comment]
Thank you for reporting this. I have opened a PR (#13607) which should fix it.

**Comment by elfin-sbreuers** [comment]
@javiereguiluz: The merge request only solved the issue for 3.4. The issue still exists for the documentation of 4.4, 5.0, and 5.1. There is also a small typo in the documentation now: `provied` --> `provided`.

**Comment by javiereguiluz** [comment]
@elfin-sbreuers thanks for telling us. Could you please create a pull request against Symfony 4.4 to fix this issue? Thanks!

**Comment by cavasinf** [comment]
I don't understand why the doc still showing the wrong code.

The PR is not OP for Symf 4.4 ?
https://symfony.com/doc/4.4/bundles/extension.html#creating-an-extension-class
