### ISSUE TITLE
[Symfony website] JS/CSS issues with main menu

### ISSUE THREAD

**Issue by dirkluijk** [symfony/symfony-docs#4324]
Hi,

I didn't know where to report this, so I do it here. 

There are issues with the main menu on the Symfony.com website:
- The menu is set to 'fixed' too soon (the threshold must be 40px higher).
- When the menu becomes 'fixed', extra padding (40px) needs to be added to the underlaying page (``content_wrapper``or ``container``), to keep the content on the same position.

If needed I can provide screenshots, but if you try, you can see it for yourself.

ping @javiereguiluz

**Comment by javiereguiluz** [comment]
Hopefully, this problem has been solved. I've tested it in the documentation section and in the blog. Everything seems to work as expected. If you agree, please close this issue. If not, please provide more details about the error. Thanks.

**Comment by dirkluijk** [comment]
It looks like it is still happening. I have created some screenshots. The first screenshot is at a page offset of [0, 90], the second at [0, 91]. As you can see, the nav (which has a height of 40px) gets fixed, causing the "underlaying" contents to move up 40px. An extra padding of 40px should be applied to the body when the nav gets fixed.

![symfony-site-1](https://cloud.githubusercontent.com/assets/2102973/5612234/df558594-94d1-11e4-93d8-983972f57347.jpg)
![symfony-site-2](https://cloud.githubusercontent.com/assets/2102973/5612235/df56607c-94d1-11e4-833a-3ff550bc1827.jpg)

It may be a small issue, but it's not nice when scrolling slowly and it seems quite easy too fix.

**Comment by dirkluijk** [comment]
This is how it should be, IMHO.

![symfony-site-3](https://cloud.githubusercontent.com/assets/2102973/5612384/200cff34-94d4-11e4-9b7c-6585f9f5d15f.jpg)
![symfony-site-4](https://cloud.githubusercontent.com/assets/2102973/5612385/200f5810-94d4-11e4-86c4-c50f249201cd.jpg)

**Comment by javiereguiluz** [comment]
@dirkluijk thanks to your diagrams I finally managed to fully understand the problem. This is now fixed thanks to your suggestion of using a `123px` offset. It will be online on symfony.com after the next website deploy.

**Comment by javiereguiluz** [comment]
@dirkluijk the new website has been deployed and this issue hopefully is fixed now.

**Comment by dirkluijk** [comment]
Looks good! :+1: 

Just a few small improvements for tablet/mobile viewports:
- On screens smaller than 970px, the SensioLabs bar does not stick with the window. This causes the navbar to get fixed too soon. In other words, the treshhold value must be about 40px higher then.
- On screens smaller than 786px, the navbar does not get "sticky" but stays on top of the page. The extra padding of 40px should then not be added. 

With this additions it 'll be perfect!

**Comment by javiereguiluz** [comment]
@dirkluijk thanks for reporting these new errors. A new pull request has been prepared for symfony.com source code and everything will be fixed soon after the next website deploy. I'll keep you posted.

**Comment by javiereguiluz** [comment]
@dirkluijk the fixes have been deployed and I think we could consider this issue as fixed. If you agree, please close this issue. Thanks!
