### ISSUE TITLE
Length of lines can cause a weird wrap

### ISSUE THREAD

**Issue by iltar** [symfony/symfony-docs#6910]
Some times the line length becomes too much and gets cut off, this is not the same for everyone but it so happened to me. Possibly related to #6742

_http://symfony.com/doc/current/controller/argument_value_resolver.html_
![](http://i.imgur.com/iRUHHbY.png)

**Comment by javiereguiluz** [comment]
And this is much worse in pages like this one: http://symfony.com/doc/current/reference/configuration/doctrine.html

In the past I tried to fix this several times. This morning I committed a new solution to symfony.com and it will be available after the next deploy. I've tested successfully in several browsers, so I'm confident this will be gone for once and for all.

I'm closing this as "fixed" then. Thanks.

**Comment by iltar** [comment]
@javiereguiluz when will this be visible? I've just checked the page I linked originally and the one you've linked, it's still present for me.

**Comment by wouterj** [comment]
looks fixed to me now

**Comment by iltar** [comment]
Yup just checked again, it looks fixed, thanks!
