### ISSUE TITLE
Some property values are incorrect.

### ISSUE THREAD

**Issue by tkinali** [symfony/symfony-docs#9116]
The default value of the strict property of the Choice Constraint still appears `false` in the [4.x documentation](http://symfony.com/doc/current/reference/constraints/Choice.html#strict). But it is defined as true in the [source code](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Constraints/Choice.php). 

Also the `type` of the [missingFieldsMessage](http://symfony.com/doc/current/reference/constraints/Collection.html#missingfieldsmessage) property of the Collection Constraint appears boolean. I think it should be a `string`. This applies to documentation of all versions.

**Comment by javiereguiluz** [comment]
Thanks for reporting these errors. We're fixing them in #9162 and #9163.

**Comment by javiereguiluz** [comment]
#9162 and #9163 are merged, so this is now fixed. Thanks!

**Comment by tkinali** [comment]
Hi Javier,

Second bug still persists other than 2.7.

[2.8](http://symfony.com/doc/2.8/reference/constraints/Collection.html#missingfieldsmessage), [3.3](http://symfony.com/doc/3.3/reference/constraints/Collection.html#missingfieldsmessage), [3.4](http://symfony.com/doc/3.4/reference/constraints/Collection.html#missingfieldsmessage), [4.0](http://symfony.com/doc/current/reference/constraints/Collection.html#missingfieldsmessage) and [4.1](http://symfony.com/doc/master/reference/constraints/Collection.html#missingfieldsmessage)

**Comment by xabbuh** [comment]
@tkinali We merge branches up on a regular basis, but not after every pull request we merge. So this will *soon* be available in all maintained versions of the documentation. :)
